#vARIABLE NAMES

# A variable name must start with a letter or an underscore character
# A variable name cannot start with a number
# A variable name can only contain alpha-numeric characters and under scores
# (A-Z , 0 - 9 , and -)

# Variable names are case sensitive
# (age, Age and AGE are three different variables)

# A variable name cannot be any of the python keywords.

# Legal variable names
myvar = "Alfiya"
my_var = "Zaara"
_my_var = "Fadil"
myVar = "Shad"
MYVAR = 123
myvar2 = 234

print(myvar)
print(my_var)
print(_my_var)
print(myVar)
print(MYVAR)
print(myvar2)